---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CBMAT: Copula Based Multivariate Association Test for bivariate mixed phenotypes

<!-- badges: start -->
<!-- badges: end -->

## Installation

``` {r, eval=F, echo=F}
# stable version from CRAN
install.packages("CBMAT")
```

``` r
# development version from GitHub
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("julstpierre/CBMAT")
```
## Example

```{r}
attach(data_mixed)
mixed.fit <-CBMAT(y1=y.bin,
                  fam1="binomial(link=probit)",
                  y2=y.Gamma,
                  fam2="Gamma(link=log)",
                  x=x,
                  G=G,
                  copfit=c("Gaussian","Clayton","Franck","Gumbell"),
                  weight=FALSE,
                  weight.para1=1,
                  weight.para2=25,
                  pval.method="min"
)

mixed.fit

cont.fit <-CBMAT(y1=y.gauss,
                 fam1="gaussian()",
                 y2=y.Gamma,
                 fam2="Gamma(link=log)",
                 x=x,
                 G=G,
                 copfit=c("Gaussian","Clayton","Franck","Gumbell"),
                 weight=FALSE,
                 weight.para1=1,
                 weight.para2=25,
                 pval.method="min"
)
cont.fit
```
